
package pe.edu.upc.dsd.taxiempresarial.wsdlservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceTaxyEmpSoap", targetNamespace = "http://localhost/WebServiceTaxyEmp")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceTaxyEmpSoap {


    /**
     * 
     * @param fecha
     * @param codEmp
     * @return
     *     returns localhost.webservicetaxyemp.ArrayOfTaxyServicioEntity
     */
    @WebMethod(operationName = "ConsultarServicioRutaDisponiblePorDia", action = "http://localhost/WebServiceTaxyEmp/ConsultarServicioRutaDisponiblePorDia")
    @WebResult(name = "ConsultarServicioRutaDisponiblePorDiaResult", targetNamespace = "http://localhost/WebServiceTaxyEmp")
    @RequestWrapper(localName = "ConsultarServicioRutaDisponiblePorDia", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ConsultarServicioRutaDisponiblePorDia")
    @ResponseWrapper(localName = "ConsultarServicioRutaDisponiblePorDiaResponse", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ConsultarServicioRutaDisponiblePorDiaResponse")
    public ArrayOfTaxyServicioEntity consultarServicioRutaDisponiblePorDia(
        @WebParam(name = "fecha", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        XMLGregorianCalendar fecha,
        @WebParam(name = "codEmp", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        int codEmp);

    /**
     * 
     * @param codServicio
     * @param codUser
     * @return
     *     returns int
     */
    @WebMethod(operationName = "ReservarServicioRuta", action = "http://localhost/WebServiceTaxyEmp/ReservarServicioRuta")
    @WebResult(name = "ReservarServicioRutaResult", targetNamespace = "http://localhost/WebServiceTaxyEmp")
    @RequestWrapper(localName = "ReservarServicioRuta", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ReservarServicioRuta")
    @ResponseWrapper(localName = "ReservarServicioRutaResponse", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ReservarServicioRutaResponse")
    public int reservarServicioRuta(
        @WebParam(name = "codUser", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        int codUser,
        @WebParam(name = "codServicio", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        int codServicio);

    /**
     * 
     * @param codUser
     * @return
     *     returns localhost.webservicetaxyemp.ArrayOfTaxyReservaEntity
     */
    @WebMethod(operationName = "ConsultarServicioRutaDisponiblePorUsuario", action = "http://localhost/WebServiceTaxyEmp/ConsultarServicioRutaDisponiblePorUsuario")
    @WebResult(name = "ConsultarServicioRutaDisponiblePorUsuarioResult", targetNamespace = "http://localhost/WebServiceTaxyEmp")
    @RequestWrapper(localName = "ConsultarServicioRutaDisponiblePorUsuario", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ConsultarServicioRutaDisponiblePorUsuario")
    @ResponseWrapper(localName = "ConsultarServicioRutaDisponiblePorUsuarioResponse", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.ConsultarServicioRutaDisponiblePorUsuarioResponse")
    public ArrayOfTaxyReservaEntity consultarServicioRutaDisponiblePorUsuario(
        @WebParam(name = "codUser", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        int codUser);

    /**
     * 
     * @param codReserva
     * @return
     *     returns int
     */
    @WebMethod(operationName = "CancelarReservaRuta", action = "http://localhost/WebServiceTaxyEmp/CancelarReservaRuta")
    @WebResult(name = "CancelarReservaRutaResult", targetNamespace = "http://localhost/WebServiceTaxyEmp")
    @RequestWrapper(localName = "CancelarReservaRuta", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.CancelarReservaRuta")
    @ResponseWrapper(localName = "CancelarReservaRutaResponse", targetNamespace = "http://localhost/WebServiceTaxyEmp", className = "localhost.webservicetaxyemp.CancelarReservaRutaResponse")
    public int cancelarReservaRuta(
        @WebParam(name = "codReserva", targetNamespace = "http://localhost/WebServiceTaxyEmp")
        int codReserva);

}
