
package pe.edu.upc.dsd.taxiempresarial.wsdlservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceTaxyEmp", targetNamespace = "http://localhost/WebServiceTaxyEmp", wsdlLocation = "http://localhost:3779/ServicioWeb.asmx?wsdl")
public class WebServiceTaxyEmp
    extends Service
{

    private final static URL WEBSERVICETAXYEMP_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICETAXYEMP_EXCEPTION;
    private final static QName WEBSERVICETAXYEMP_QNAME = new QName("http://localhost/WebServiceTaxyEmp", "WebServiceTaxyEmp");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:3779/ServicioWeb.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICETAXYEMP_WSDL_LOCATION = url;
        WEBSERVICETAXYEMP_EXCEPTION = e;
    }

    public WebServiceTaxyEmp() {
        super(__getWsdlLocation(), WEBSERVICETAXYEMP_QNAME);
    }

    public WebServiceTaxyEmp(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICETAXYEMP_QNAME, features);
    }

    public WebServiceTaxyEmp(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICETAXYEMP_QNAME);
    }

    public WebServiceTaxyEmp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICETAXYEMP_QNAME, features);
    }

    public WebServiceTaxyEmp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceTaxyEmp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceTaxyEmpSoap
     */
    @WebEndpoint(name = "WebServiceTaxyEmpSoap")
    public WebServiceTaxyEmpSoap getWebServiceTaxyEmpSoap() {
        return super.getPort(new QName("http://localhost/WebServiceTaxyEmp", "WebServiceTaxyEmpSoap"), WebServiceTaxyEmpSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceTaxyEmpSoap
     */
    @WebEndpoint(name = "WebServiceTaxyEmpSoap")
    public WebServiceTaxyEmpSoap getWebServiceTaxyEmpSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/WebServiceTaxyEmp", "WebServiceTaxyEmpSoap"), WebServiceTaxyEmpSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceTaxyEmpSoap
     */
    @WebEndpoint(name = "WebServiceTaxyEmpSoap12")
    public WebServiceTaxyEmpSoap getWebServiceTaxyEmpSoap12() {
        return super.getPort(new QName("http://localhost/WebServiceTaxyEmp", "WebServiceTaxyEmpSoap12"), WebServiceTaxyEmpSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceTaxyEmpSoap
     */
    @WebEndpoint(name = "WebServiceTaxyEmpSoap12")
    public WebServiceTaxyEmpSoap getWebServiceTaxyEmpSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://localhost/WebServiceTaxyEmp", "WebServiceTaxyEmpSoap12"), WebServiceTaxyEmpSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICETAXYEMP_EXCEPTION!= null) {
            throw WEBSERVICETAXYEMP_EXCEPTION;
        }
        return WEBSERVICETAXYEMP_WSDL_LOCATION;
    }

}
